AllCops:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'app/geo/calculator.rb'

Metrics/LineLength:
  Exclude:
    - 'app/geo/calculator.rb'
